### ISSUE TITLE
Ajout de podcast non hébergé : Pouvoir éditer ses informations.

### ISSUE THREAD

**Issue by Nemotaku** [BadGeek-Dev/badgeek-v4#23]
Actuellement, une fois le podcast non hébergé créé , il n'est plus possible de modifier ses informations/ré-accéder au formulaire. Il faudrait pouvoir modifier n'importe quel champ à l'exception du flux RSS. 

Toute modification entraîne une validation manuelle.

**Comment by ggekos** [comment]
Voilà la pr #28
