### ISSUE TITLE
Administration : Création de podcast hébergé.

### ISSUE THREAD

**Issue by Nemotaku** [BadGeek-Dev/badgeek-v4#25]
Lors de l'ajout d'un podcast, proposer le choix entre non hébergé (ce qui a été dev jusqu'à présent) et hébergé. (l'objet de cette issue) 

La validation du concept se fait toujours par un admin. Un concept non hébergé est la même chose qu'un non hébergé sauf qu'il nous fournit pas son flux RSS.

**Comment by ggekos** [comment]
rien à voir, avec le ticket, mais comme cela se verra lors de la review -> la gestion des migrations est à réécrire. L'application des migrations est hasardeux. Il serait bien de stocker en base de donnée toutes les migrations effectués et pas uniquement la version actuelle. (C'est le fonctionnement avec les migrations symfony)
