### ISSUE TITLE
Administration : Ajout d'un épisode d'un podcast non hébergé

### ISSUE THREAD

**Issue by Nemotaku** [BadGeek-Dev/badgeek-v4#26]
L'ajout d'épisode se fait ensuite avec un formulaire en 3 étapes : 

- Etape 1 : Choix du concept 

- Etape 2 : Formulaire de l'épisode
- Numéro de la saison (pré-rempli en fonction du dernier épisode du concept)
- Numéro de l'épisode (pré-rempli en fonction du dernier épisode du concept) 
- Titre de l'épisode 
- Description 
- Auteurs
- Date de publication automatique (on gérera la post publication dans une prochaine issue)
- Tags
- Upload du fichier de l'épisode. Seul les fichiers MP3 sont acceptés.

- Etape 3 : Etape de validation finale,
Les infos précedentes sont résumées et en fonction du fichier, on déduit durée de l'épisode et son poids en bytes. (Des infos dont on aura besoin pour le flux RSS, qui idem sera l'occasion d'une prochaine issue). 
SI l'utilisateur ne valide pas quelque soit le moyen, son fichier est supprimé.

**Comment by ggekos** [comment]
je le fais dans la meme branch que #25
