### ISSUE TITLE
Pouvoir éditer les informations d'un podcast en cours d'approbation.

### ISSUE THREAD

**Issue by Nemotaku** [BadGeek-Dev/badgeek-v4#40]
Un utilisateur doit pouvoir éditer les informations de son podcast même si il est en cours d'approbation.

**Comment by ggekos** [comment]
https://github.com/BadGeek-Dev/badgeek-v4/commit/2e5182b5c3ea1186d3bc6ea5c2fde3a71142d49b

voilà
