### ISSUE TITLE
Moteur de recherche - Recherche simple

### ISSUE THREAD

**Issue by Nemotaku** [BadGeek-Dev/badgeek-v4#54]
Pouvoir faire des recherches. via un menu en haut. 

La recherche simple fait une recherche parmis toutes les données suivantes : 
- Titre du podcast ou d'un épisode
- Description du podcast ou d'un épisode
- Tags du podcast ou d'un épisode
- Auteur du podcast ou d'un épisode

**Comment by ggekos** [comment]
Tu confirmes qu'on peut pas installer un elasticsearch sur la machine ?
