### ISSUE TITLE
Tags - Utilisation d'une table à part

### ISSUE THREAD

**Issue by Nemotaku** [BadGeek-Dev/badgeek-v4#56]
Gérer les tags par 2 tables "tags_podcast", "tags_episodes" contenant l'id du podcast/épisode et le tag associé.

**Comment by ggekos** [comment]
Je pense qu'il est pas vraiment utile de faire une table de liaison.
Stocker les tags sous forme d'un tableau serializé est suffisant.

**Comment by Nemotaku** [comment]
Ok
